Footer and contact section
richy4dev/My-Personal-Portfolio pull request #3
Opened 2022-08-24 14:26 UTC by richy4dev

In this branch, my partners and I:
- Added a footer section.
- Added a contact form section.
- Ensured workability of form using formspree.io

2022-08-24 15:02 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi Team,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please add all collaborators names and social links to the `Authors` section in your README file to make it more professional.

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-08-24 15:02 UTC, omar-muhamad commented on index.html
> +         required=""
- [ ] The `required` attribute doesn't work right now, So please remove the `=` and `""` to make it work as expected.

2022-08-24 15:02 UTC, omar-muhamad commented on style.css
> +  flex-direction: column;
- For the contact form styling please fix the following to make your design match the given Figma design:
- [ ] Please add the correct margin value between the contact form and the `about me` section above it.
- [ ] Please fix the color issue in the top left corner of the contact form.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/186450135-1d8b97e1-51ff-41f9-8961-f6807118d6fa.png)  | ![image](https://user-images.githubusercontent.com/68796232/186449959-a0a27f17-e756-46aa-9dd3-a6e49da452b1.png)  |

2022-08-24 15:02 UTC, omar-muhamad commented on index.html
> +         required=""
- For the contact form styling please fix the following to make your design match the given Figma design:
- [ ] Please add the correct width, height, and margins values for all input fields and fix the `Get In Touch` button placement.
- [ ] Please fix the placeholder for the text area input field because it;s not appearing and try to stick as much as possible to the given Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/186452145-d79eff8a-32c5-4dea-bb55-d539afe7f3f4.png)  | ![image](https://user-images.githubusercontent.com/68796232/186452413-911b40a7-f732-4c90-94ed-3990183e9054.png)  |

2022-08-25 11:26 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @richy4dev 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] **As mentioned by the previous reviewer, Please add all collaborators' names and social links to the Authors section in your README file to make it more professional.**
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 11:26 UTC, tresorsawasawa commented on style.css
> +
- [ **OPTIONAL** ] Kindly make sure you also add the missing **Horizontal line** at the bottom of your page to stick to the Figma design.

2022-08-25 13:34 UTC, Munsa1 approved these changes
Hi @richy4dev, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 13:56 UTC, merged